# Restaurent review Sentiment analysis with LSTM Project
Data analysis, preprocessing, training, and model saving.

In [16]:
import pandas as pd
import numpy as np
import re
import pickle

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\harsh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [17]:
df = pd.read_csv("../data/Restaurant_Reviews.tsv", sep='\t')

df.head()

                                              Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [18]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)

    words = text.split()

    words = [word for word in words if word not in stop_words]

    return " ".join(words)

df['Review'] = df['Review'].apply(clean_text)

df.head()

                                              Review  Liked
0                                    wow loved place      1
1                                         crust good      0
2                                tasty texture nasty      0
3  stopped late may bank holiday rick steve recom...      1
4                        selection menu great prices      1

In [19]:
X = df['Review']
y = df['Liked']

In [20]:
max_words = 5000

tokenizer = Tokenizer(num_words=max_words)

tokenizer.fit_on_texts(X)

sequences = tokenizer.texts_to_sequences(X)

In [21]:
max_length = 50

X_pad = pad_sequences(
    sequences,
    maxlen=max_length,
    padding='post'
)

print(X_pad.shape)

(1000, 50)

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
    X_pad,
    y,
    test_size=0.2,
    random_state=42
)

In [23]:
model = Sequential()

model.add(
    Embedding(
        input_dim=max_words,
        output_dim=128,
        input_length=max_length
    )
)

model.add(LSTM(128))

model.add(Dropout(0.5))

model.add(Dense(1, activation='sigmoid'))

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

c:\Users\harsh\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
history = model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_data=(X_test, y_test)
)

Epoch 1/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 4s 61ms/step - accuracy: 0.4762 - loss: 0.6971 - val_accuracy: 0.4800 - val_loss: 0.6933
Epoch 2/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.5075 - loss: 0.6957 - val_accuracy: 0.4800 - val_loss: 0.6960
Epoch 3/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.5050 - loss: 0.6941 - val_accuracy: 0.4800 - val_loss: 0.6944
Epoch 4/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.5013 - loss: 0.6929 - val_accuracy: 0.5200 - val_loss: 0.6928
Epoch 5/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.5013 - loss: 0.6956 - val_accuracy: 0.4800 - val_loss: 0.6932
Epoch 6/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.4787 - loss: 0.6948 - val_accuracy: 0.4800 - val_loss: 0.6944
Epoch 7/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.5075 - loss: 0.6942 - val_accuracy: 0.4800 - val_loss: 0.6939
Epoch 8/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.4725 - loss: 0.6947 - val_accuracy: 0.4800 - val_loss: 0.6933
Epoch 9/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.4875 - loss: 0.6953 - val_accuracy: 0.4800 - val_loss: 0.6938
Epoch 10/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.5163 - loss: 0.6939 - val_accuracy: 0.4800 - val_loss: 0.6933
Epoch 11/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - accuracy: 0.4900 - loss: 0.6947 - val_accuracy: 0.4800 - val_loss: 0.6937
Epoch 12/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.5075 - loss: 0.6928 - val_accuracy: 0.4800 - val_loss: 0.6936
Epoch 13/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.4975 - loss: 0.6940 - val_accuracy: 0.4800 - val_loss: 0.6946
Epoch 14/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.4875 - loss: 0.6948 - val_accuracy: 0.4800 - val_loss: 0.6934
Epoch 15/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.5163 - loss: 0.6933 - val_accuracy: 0.4800 - val_loss: 0.6944
Epoch 16/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.4888 - loss: 0.6940 - val_accuracy: 0.4800 - val_loss: 0.6934
Epoch 17/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.5200 - loss: 0.6927 - val_accuracy: 0.4800 - val_loss: 0.6938
Epoch 18/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.4787 - loss: 0.6954 - val_accuracy: 0.4800 - val_loss: 0.6957
Epoch 19/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.4950 - loss: 0.6940 - val_accuracy: 0.5200 - val_loss: 0.6928
Epoch 20/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.5000 - loss: 0.6951 - val_accuracy: 0.4800 - val_loss: 0.6936
Epoch 21/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.5050 - loss: 0.6941 - val_accuracy: 0.4800 - val_loss: 0.6932
Epoch 22/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.5075 - loss: 0.6937 - val_accuracy: 0.4800 - val_loss: 0.6935
Epoch 23/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.4800 - loss: 0.6945 - val_accuracy: 0.5200 - val_loss: 0.6930
Epoch 24/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.4913 - loss: 0.6934 - val_accuracy: 0.4800 - val_loss: 0.6926
Epoch 25/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - accuracy: 0.7400 - loss: 0.5660 - val_accuracy: 0.7100 - val_loss: 0.7312
Epoch 26/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.8813 - loss: 0.3593 - val_accuracy: 0.7400 - val_loss: 0.7107
Epoch 27/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9225 - loss: 0.2307 - val_accuracy: 0.7750 - val_loss: 0.6820
Epoch 28/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.9600 - loss: 0.1549 - val_accuracy: 0.7950 - val_loss: 0.6686
Epoch 29/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - accuracy: 0.9538 - loss: 0.1725 - val_accuracy: 0.7650 - val_loss: 0.7289
Epoch 30/30
25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.9688 - loss: 0.1284 - val_accuracy: 0.7600 - val_loss: 0.7298

In [27]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Accuracy:", accuracy)

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.7600 - loss: 0.7298
Accuracy: 0.7599999904632568

In [32]:
model.save("../models/lstm_sentiment_model.keras")

In [30]:
with open("../models/tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)